#pragma once

#define GLAPP_OSD_COMMON_SOURCE_STRING "osd_common_shader"
#define GLAPP_OSD_VERTEX_SOURCE_STRING "osd_vertex_shader"
#define GLAPP_OSD_TESS_CONTROL_SOURCE_STRING "osd_tess_control_shader"
#define GLAPP_OSD_TESS_EVAL_SOURCE_STRING "osd_tess_eval_shader"

#define GLAPP_CONFIG_WINDOW "Window."
#define GLAPP_CONFIG_GRAPHICS "Graphics."
#define GLAPP_CONFIG_UI "UI."

#define GLAPP_CONFIG_FULLSCREEN "full_screen"
#define GLAPP_CONFIG_RESOLUTION_X "resolution_x"
#define GLAPP_CONFIG_RESOLUTION_Y "resolution_y"
#define GLAPP_CONFIG_FOV "fov"
#define GLAPP_CONFIG_VSYNC "vsync"
#define GLAPP_CONFIG_PATCH_TYPE_GREGORY "osd_patch_type_gregory"
#define GLAPP_CONFIG_PATCH_LEVEL_DEFAULT "osd_patch_level_default"
#define GLAPP_CONFIG_PATCH_LEVEL_MAX "osd_patch_level_max"
#define GLAPP_CONFIG_TESS_LEVEL_DEFAULT "osd_tess_level_default"
#define GLAPP_CONFIG_TESS_LEVEL_MAX "osd_tess_level_max"
#define GLAPP_CONFIG_USER_INTERFACE "user_interface"
#define GLAPP_CONFIG_FONT_FILE "font_file"
#define GLAPP_CONFIG_FONT_SIZE "font_size"
#define GLAPP_CONFIG_FONT_COLOR "font_color"
